/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AutocompleteAccount: typeof import('./src/components/df-autocomplete/AutocompleteAccount.vue')['default']
    Bar: typeof import('./src/components/df-chart/Bar.vue')['default']
    Grid: typeof import('./src/components/grid/Grid.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputDate: typeof import('./src/components/df-input/InputDate.vue')['default']
    InputFilter: typeof import('./src/components/df-input/InputFilter.vue')['default']
    InputMoney: typeof import('./src/components/df-input/InputMoney.vue')['default']
    InputPeriod: typeof import('./src/components/df-input/InputPeriod.vue')['default']
    Line: typeof import('./src/components/df-chart/Line.vue')['default']
    Loading: typeof import('./src/components/loading/Loading.vue')['default']
    OutputText: typeof import('./src/components/df-output/OutputText.vue')['default']
    Period: typeof import('./src/components/df-period/Period.vue')['default']
    Pie: typeof import('./src/components/df-chart/Pie.vue')['default']
    ResultLayout: typeof import('./src/components/df-layout/ResultLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
