/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/location/Location': RouteRecordInfo<'/location/Location', '/location/Location', Record<never, never>, Record<never, never>>,
    '/location/LocationForm': RouteRecordInfo<'/location/LocationForm', '/location/LocationForm', Record<never, never>, Record<never, never>>,
    '/location/LocationResult': RouteRecordInfo<'/location/LocationResult', '/location/LocationResult', Record<never, never>, Record<never, never>>,
    '/paymentMethod/PaymentMethod': RouteRecordInfo<'/paymentMethod/PaymentMethod', '/paymentMethod/PaymentMethod', Record<never, never>, Record<never, never>>,
    '/paymentMethod/PaymentMethodForm': RouteRecordInfo<'/paymentMethod/PaymentMethodForm', '/paymentMethod/PaymentMethodForm', Record<never, never>, Record<never, never>>,
    '/paymentMethod/PaymentMethodResult': RouteRecordInfo<'/paymentMethod/PaymentMethodResult', '/paymentMethod/PaymentMethodResult', Record<never, never>, Record<never, never>>,
    '/statement/bank/Bank': RouteRecordInfo<'/statement/bank/Bank', '/statement/bank/Bank', Record<never, never>, Record<never, never>>,
    '/statement/bank/BankForm': RouteRecordInfo<'/statement/bank/BankForm', '/statement/bank/BankForm', Record<never, never>, Record<never, never>>,
    '/statement/bank/BankResult': RouteRecordInfo<'/statement/bank/BankResult', '/statement/bank/BankResult', Record<never, never>, Record<never, never>>,
    '/statement/statementPattern/StatementPattern': RouteRecordInfo<'/statement/statementPattern/StatementPattern', '/statement/statementPattern/StatementPattern', Record<never, never>, Record<never, never>>,
    '/statement/statementPattern/StatementPatternForm': RouteRecordInfo<'/statement/statementPattern/StatementPatternForm', '/statement/statementPattern/StatementPatternForm', Record<never, never>, Record<never, never>>,
    '/statement/statementPattern/StatementPatternResult': RouteRecordInfo<'/statement/statementPattern/StatementPatternResult', '/statement/statementPattern/StatementPatternResult', Record<never, never>, Record<never, never>>,
    '/statement/statementType/StatementType': RouteRecordInfo<'/statement/statementType/StatementType', '/statement/statementType/StatementType', Record<never, never>, Record<never, never>>,
    '/statement/statementType/StatementTypeForm': RouteRecordInfo<'/statement/statementType/StatementTypeForm', '/statement/statementType/StatementTypeForm', Record<never, never>, Record<never, never>>,
    '/statement/statementType/StatementTypeResult': RouteRecordInfo<'/statement/statementType/StatementTypeResult', '/statement/statementType/StatementTypeResult', Record<never, never>, Record<never, never>>,
    '/structure/Structure': RouteRecordInfo<'/structure/Structure', '/structure/Structure', Record<never, never>, Record<never, never>>,
    '/structure/StructureHeader': RouteRecordInfo<'/structure/StructureHeader', '/structure/StructureHeader', Record<never, never>, Record<never, never>>,
    '/structure/StructureMessaging': RouteRecordInfo<'/structure/StructureMessaging', '/structure/StructureMessaging', Record<never, never>, Record<never, never>>,
    '/summary/Summary': RouteRecordInfo<'/summary/Summary', '/summary/Summary', Record<never, never>, Record<never, never>>,
    '/supermarket/Supermarket': RouteRecordInfo<'/supermarket/Supermarket', '/supermarket/Supermarket', Record<never, never>, Record<never, never>>,
    '/transaction/account/Account': RouteRecordInfo<'/transaction/account/Account', '/transaction/account/Account', Record<never, never>, Record<never, never>>,
    '/transaction/account/AccountForm': RouteRecordInfo<'/transaction/account/AccountForm', '/transaction/account/AccountForm', Record<never, never>, Record<never, never>>,
    '/transaction/account/AccountResult': RouteRecordInfo<'/transaction/account/AccountResult', '/transaction/account/AccountResult', Record<never, never>, Record<never, never>>,
    '/transaction/objective/Objective': RouteRecordInfo<'/transaction/objective/Objective', '/transaction/objective/Objective', Record<never, never>, Record<never, never>>,
    '/transaction/objective/ObjectiveForm': RouteRecordInfo<'/transaction/objective/ObjectiveForm', '/transaction/objective/ObjectiveForm', Record<never, never>, Record<never, never>>,
    '/transaction/objective/ObjectiveItemResult': RouteRecordInfo<'/transaction/objective/ObjectiveItemResult', '/transaction/objective/ObjectiveItemResult', Record<never, never>, Record<never, never>>,
    '/transaction/objective/ObjectiveMovementResult': RouteRecordInfo<'/transaction/objective/ObjectiveMovementResult', '/transaction/objective/ObjectiveMovementResult', Record<never, never>, Record<never, never>>,
    '/transaction/objective/ObjectiveResult': RouteRecordInfo<'/transaction/objective/ObjectiveResult', '/transaction/objective/ObjectiveResult', Record<never, never>, Record<never, never>>,
    '/user/User': RouteRecordInfo<'/user/User', '/user/User', Record<never, never>, Record<never, never>>,
    '/vehicle/Vehicle': RouteRecordInfo<'/vehicle/Vehicle', '/vehicle/Vehicle', Record<never, never>, Record<never, never>>,
    '/wishList/WishList': RouteRecordInfo<'/wishList/WishList', '/wishList/WishList', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/location/Location.vue': {
      routes: '/location/Location'
      views: never
    }
    'src/pages/location/LocationForm.vue': {
      routes: '/location/LocationForm'
      views: never
    }
    'src/pages/location/LocationResult.vue': {
      routes: '/location/LocationResult'
      views: never
    }
    'src/pages/paymentMethod/PaymentMethod.vue': {
      routes: '/paymentMethod/PaymentMethod'
      views: never
    }
    'src/pages/paymentMethod/PaymentMethodForm.vue': {
      routes: '/paymentMethod/PaymentMethodForm'
      views: never
    }
    'src/pages/paymentMethod/PaymentMethodResult.vue': {
      routes: '/paymentMethod/PaymentMethodResult'
      views: never
    }
    'src/pages/statement/bank/Bank.vue': {
      routes: '/statement/bank/Bank'
      views: never
    }
    'src/pages/statement/bank/BankForm.vue': {
      routes: '/statement/bank/BankForm'
      views: never
    }
    'src/pages/statement/bank/BankResult.vue': {
      routes: '/statement/bank/BankResult'
      views: never
    }
    'src/pages/statement/statementPattern/StatementPattern.vue': {
      routes: '/statement/statementPattern/StatementPattern'
      views: never
    }
    'src/pages/statement/statementPattern/StatementPatternForm.vue': {
      routes: '/statement/statementPattern/StatementPatternForm'
      views: never
    }
    'src/pages/statement/statementPattern/StatementPatternResult.vue': {
      routes: '/statement/statementPattern/StatementPatternResult'
      views: never
    }
    'src/pages/statement/statementType/StatementType.vue': {
      routes: '/statement/statementType/StatementType'
      views: never
    }
    'src/pages/statement/statementType/StatementTypeForm.vue': {
      routes: '/statement/statementType/StatementTypeForm'
      views: never
    }
    'src/pages/statement/statementType/StatementTypeResult.vue': {
      routes: '/statement/statementType/StatementTypeResult'
      views: never
    }
    'src/pages/structure/Structure.vue': {
      routes: '/structure/Structure'
      views: never
    }
    'src/pages/structure/StructureHeader.vue': {
      routes: '/structure/StructureHeader'
      views: never
    }
    'src/pages/structure/StructureMessaging.vue': {
      routes: '/structure/StructureMessaging'
      views: never
    }
    'src/pages/summary/Summary.vue': {
      routes: '/summary/Summary'
      views: never
    }
    'src/pages/supermarket/Supermarket.vue': {
      routes: '/supermarket/Supermarket'
      views: never
    }
    'src/pages/transaction/account/Account.vue': {
      routes: '/transaction/account/Account'
      views: never
    }
    'src/pages/transaction/account/AccountForm.vue': {
      routes: '/transaction/account/AccountForm'
      views: never
    }
    'src/pages/transaction/account/AccountResult.vue': {
      routes: '/transaction/account/AccountResult'
      views: never
    }
    'src/pages/transaction/objective/Objective.vue': {
      routes: '/transaction/objective/Objective'
      views: never
    }
    'src/pages/transaction/objective/ObjectiveForm.vue': {
      routes: '/transaction/objective/ObjectiveForm'
      views: never
    }
    'src/pages/transaction/objective/ObjectiveItemResult.vue': {
      routes: '/transaction/objective/ObjectiveItemResult'
      views: never
    }
    'src/pages/transaction/objective/ObjectiveMovementResult.vue': {
      routes: '/transaction/objective/ObjectiveMovementResult'
      views: never
    }
    'src/pages/transaction/objective/ObjectiveResult.vue': {
      routes: '/transaction/objective/ObjectiveResult'
      views: never
    }
    'src/pages/user/User.vue': {
      routes: '/user/User'
      views: never
    }
    'src/pages/vehicle/Vehicle.vue': {
      routes: '/vehicle/Vehicle'
      views: never
    }
    'src/pages/wishList/WishList.vue': {
      routes: '/wishList/WishList'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
